# -*- mode: ruby -*-
# vi: set ft=ruby :

# Check required plugins
REQUIRED_PLUGINS_LIBVIRT = %w(vagrant-libvirt)
exit unless REQUIRED_PLUGINS_LIBVIRT.all? do |plugin|
    Vagrant.has_plugin?(plugin) || (
        puts "The #{plugin} plugin is required.  Please install it with:"
        puts "$ vagrant plugin install #{plugin}"
        false
    )
end

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    # change the storage pool for libvirt to use the larger disk
    config.vm.provider :libvirt do |libvirt|
        libvirt.storage_pool_name = "local"
    end

    # Test VM
    config.vm.define "module" do |node|
        node.vm.hostname = "module"
        node.vm.box = "generic/ubuntu1804"
        # node.vm.box = "midgard_img"
        node.vm.box_check_update = false
        node.vm.network "private_network", ip: "192.168.18.15"
        node.vm.provider :libvirt do |domain|
            domain.memory = 1024
            domain.nested = true
            domain.nic_model_type = "e1000"
        end
        node.vm.synced_folder '../arraypriorityqueue', '/vagrant', type: 'rsync', rsync__auto: true
    end

    # set the synced folders
    # config.vm.synced_folder './', '/vagrant', type: 'nfs'
end
